// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPiW51rzmbxpkgrg9hj-JjfEVLQ3D2ofo',
    appId: '1:33696000994:web:2dffc9bef5c66b765067bb',
    messagingSenderId: '33696000994',
    projectId: 'cardinal-realty-2975d',
    authDomain: 'cardinal-realty-2975d.firebaseapp.com',
    storageBucket: 'cardinal-realty-2975d.appspot.com',
    measurementId: 'G-X941GXCHNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn1QRA-Z1-TPAM2QwufGSEhm94sjGrxx0',
    appId: '1:33696000994:android:bd1f38f6bf9a8b045067bb',
    messagingSenderId: '33696000994',
    projectId: 'cardinal-realty-2975d',
    storageBucket: 'cardinal-realty-2975d.appspot.com',
  );
}
